"""
test_phase5_properties.py
=========================
Property-based tests for Phase 5 GeoJSON serialization.

**Validates: Requirements 6.4**

Property 6: Serialização preserva decision e reason
----------------------------------------------------
For any PartnerMetrics with decision and reason filled in, the PARTNER_POINT
feature generated by _write_geojson() logic must have the same values in
properties.decision and properties.reason.

The helper build_partner_point_feature() replicates the PARTNER_POINT feature
construction from _write_geojson() so we can test it without complex I/O setup.
"""

from __future__ import annotations

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from hypothesis import given, settings
from hypothesis import strategies as st

from models import PartnerMetrics


# ---------------------------------------------------------------------------
# Helper — replicates PARTNER_POINT feature construction from _write_geojson()
# ---------------------------------------------------------------------------

def build_partner_point_feature(p: PartnerMetrics) -> dict:
    """
    Replicates the PARTNER_POINT feature dict built inside _write_geojson().
    Used to test serialization without requiring full I/O setup.
    """
    return {
        "type": "Feature",
        "geometry": {"type": "Point", "coordinates": [p.lon, p.lat]},
        "properties": {
            "type":              "PARTNER_POINT",
            "salesforce_id":     p.salesforce_id,
            "name":              p.partner_name,
            "status":            p.status,
            "entity":            p.entity_type,
            "delivery_station":  p.station_code or "",
            "bdm":               p.bdm_cluster,
            "ctl":               p.ctl_name,
            "territory_id":      p.cluster_name,
            "decision":          p.decision,
            "reason":            p.reason,
            "matched_slot_id":   p.matched_slot_id or "",
            "cap_suggestion":    p.capacity_s,
            "radius_suggestion": p.radius_s,
            "ceps":              [],
        },
    }


# ---------------------------------------------------------------------------
# Hypothesis strategies
# ---------------------------------------------------------------------------

_decision_strategy = st.one_of(
    st.just("Go"),
    st.just("No Go"),
    st.just(""),
)

_reason_strategy = st.sampled_from([
    "Seguir cadastro",
    "Sem oportunidade próxima",
    "Sem oportunidade próxima na borda",
    "Fora de jurisdição",
    "",
])

_partner_strategy = st.builds(
    PartnerMetrics,
    origin_hex=st.just("891f1d48177ffff"),
    station_code=st.just("DSP2"),
    radius_s=st.integers(min_value=0, max_value=5000),
    capacity_s=st.integers(min_value=0, max_value=500),
    entity_type=st.sampled_from(["EXISTING", "PROSPECT", "INACTIVE_EXITED"]),
    status=st.sampled_from(["Active", "Onboarding", "BG Checks", "Prospect", "Inactive", "Exited"]),
    partner_name=st.text(max_size=50),
    salesforce_id=st.text(alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", min_size=0, max_size=18),
    decision=_decision_strategy,
    reason=_reason_strategy,
    lat=st.floats(min_value=-90.0, max_value=90.0, allow_nan=False, allow_infinity=False),
    lon=st.floats(min_value=-180.0, max_value=180.0, allow_nan=False, allow_infinity=False),
)


# ---------------------------------------------------------------------------
# Property 6 — Serialization round-trip preserves decision and reason
# ---------------------------------------------------------------------------

@settings(max_examples=200)
@given(partner=_partner_strategy)
def test_partner_point_feature_preserves_decision_and_reason(partner: PartnerMetrics):
    """
    **Validates: Requirements 6.4**

    Property 6: For any PartnerMetrics, the PARTNER_POINT feature built by
    build_partner_point_feature() must have properties.decision == p.decision
    and properties.reason == p.reason.
    """
    feature = build_partner_point_feature(partner)

    assert feature["properties"]["decision"] == partner.decision, (
        f"Expected decision='{partner.decision}', "
        f"got '{feature['properties']['decision']}'"
    )
    assert feature["properties"]["reason"] == partner.reason, (
        f"Expected reason='{partner.reason}', "
        f"got '{feature['properties']['reason']}'"
    )


@settings(max_examples=100)
@given(
    decision=_decision_strategy,
    reason=_reason_strategy,
)
def test_serialization_preserves_exact_string_values(decision: str, reason: str):
    """
    **Validates: Requirements 6.4**

    Property 6 (focused): For any combination of decision and reason values,
    the feature properties must contain the exact same string values — no
    truncation, encoding change, or substitution.
    """
    partner = PartnerMetrics(
        origin_hex="891f1d48177ffff",
        station_code="DSP2",
        radius_s=500,
        capacity_s=100,
        entity_type="PROSPECT",
        status="Prospect",
        decision=decision,
        reason=reason,
        lat=-23.5505,
        lon=-46.6333,
    )

    feature = build_partner_point_feature(partner)

    assert feature["properties"]["decision"] == decision
    assert feature["properties"]["reason"] == reason
